<?php if (!empty($this->task_added)) : ?>
    <div class="alert alert-success">
        <strong>Задача создана!</strong> Посмотреть ее можно
        <a href="/task/<?= $this->task_id ?>">здесь.</a>
    </div>
<?php endif; ?>
<?php if (!empty($this->task_edited)) : ?>
<div class="alert alert-success">
    <strong>Задача отредактирована!</strong> Посмотреть ее можно
    <a href="/task/<?= $this->task_id ?>">здесь.</a>
</div>
<?php endif; ?>

<form class="form-horizontal js-form" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label class="control-label col-sm-2" for="username">Имя</label>
        <div class="col-sm-10">
            <input name="username" type="text" class="form-control" id="username" placeholder="Введите имя" value="<?= $this->page == 'edit' ? $this->task->getUsername() : '' ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email:</label>
        <div class="col-sm-10">
            <input name="email" type="email" class="form-control" id="email" placeholder="Введите email" value="<?= $this->page == 'edit' ? $this->task->getEmail() : '' ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="title">Заголовок:</label>
        <div class="col-sm-10">
            <input name="title" type="text" class="form-control" id="title" placeholder="Введите название задачи" value="<?= $this->page == 'edit' ? $this->task->getTitle() : '' ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="description">Описание:</label>
        <div class="col-sm-10">
            <textarea name="description" class="form-control" id="description" cols="30" rows="10" placeholder="Введите текст задачи"><?= $this->page == 'edit' ? $this->task->getDescription() : '' ?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="image">Картинка:</label>
        <div class="col-sm-10">
            <input type="file" name="file" class="js-image-upload">
            <input type="hidden" name="image" class="js-image-hidden" value="<?= $this->page == 'edit' ? $this->task->getImage() : '' ?>">
        </div>
    </div>
    <?php if ($this->page == 'edit') : ?>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <input type="hidden" name="status" value="0">
                    <label>
                        <input type="checkbox" name="status" value="1" <?= $this->task->getStatus() ? 'checked' : '' ?>>
                        Статус
                    </label>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">
                <?= $this->page == 'edit' ? 'Сохранить' : 'Создать' ?>
            </button>
            <button class="btn btn-primary js-preview-btn">
                Предварительный просмотр
            </button>
        </div>
    </div>
</form>
<div class="js-preview">
</div>