<hr>
<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p class="text-center">Copyright &copy;
                <a href="http://boykodev.com/" target="_blank">Serge Boyko</a>
                <?= date('Y') ?>
            </p>
        </div>
    </div>
</footer>
</div><!-- /.container -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/assets/js/bootstrap.min.js"></script>
<!-- Custom js -->
<script src="/assets/js/script.js"></script>
</body>
</html>