<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Задачник - MVC приложение</title>

    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/css/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/task/new">Задачник</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="<?= isset($this->page) && $this->page == 'home' ? 'active' : '' ?>"><a href="/">Главная</a></li>
                <li class="<?= isset($this->page) && $this->page == 'index' ? 'active' : '' ?>"><a href="/tasks">Задачи</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if ($this->getAuth()->getUser()) : ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Здравствуйте, <?= $this->getAuth()->getUser() ?> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a class="js-logout" href="#">Выйти</a></li>
                        </ul>
                    </li>
                <?php else : ?>
                    <li class="dropdown">
                        <a href="http://phpoll.com/login" class="dropdown-toggle" data-toggle="dropdown">Вход <span class="caret"></span></a>
                        <ul class="dropdown-menu dropdown-lr animated slideInRight" role="menu">
                            <div class="col-lg-12">
                                <div class="text-center"><h3><b>Вход</b></h3></div>
                                <form class="js-login" method="post" role="form" autocomplete="off">
                                    <div class="form-group">
                                        <label for="username">Логин</label>
                                        <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Введите логин" value="" autocomplete="off">
                                    </div>

                                    <div class="form-group">
                                        <label for="password">Пароль</label>
                                        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Введите пароль" autocomplete="off">
                                    </div>

                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-xs-5 pull-right">
                                                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-success" value="Войти">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<!-- Page Content -->
<div class="container">